# Generated by Django 3.2.6 on 2021-08-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rough_pic',
            field=models.ImageField(blank=True, upload_to='blog/rough'),
        ),
    ]
