# Generated by Django 3.2.6 on 2021-08-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_thumbnail_url',
            field=models.TextField(default='http://nowhere', max_length=300),
        ),
    ]
