# Generated by Django 3.2.6 on 2021-08-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_comment_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_url', models.TextField(max_length=300, null=True)),
                ('pin_img', models.ImageField(blank=True, upload_to='pin/%Y/%m/%d')),
            ],
        ),
    ]
