# Generated by Django 3.2.6 on 2021-08-28 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_rough_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaystart', models.DateTimeField(default=django.utils.timezone.now)),
                ('switch', models.BooleanField(default=False)),
            ],
        ),
    ]
