# Generated by Django 3.2.6 on 2021-09-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RKGK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RKGK_img', models.ImageField(blank=True, upload_to='pin/%Y/%m/%d')),
            ],
        ),
    ]
