# Generated by Django 3.2 on 2022-06-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_timetracker'),
        ('blog', '0005_rkgk'),
    ]

    operations = [
    ]
