# Generated by Django 3.2 on 2022-06-27 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_0002_delete_timetracker_0005_rkgk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaystart', models.DateTimeField(default=django.utils.timezone.now)),
                ('switch', models.BooleanField(default=False)),
            ],
        ),
    ]
